server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://dayong.cnfiedqcnpon.ap-northeast-2.rds.amazonaws.com:3306/dayong?characterEncoding=UTF-8&serverTimezone
    username: admin
    password: Abcd1234


  main:
    allow-circular-references: true

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
