server:
  port: ${PORT:8080}
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # json data를 snake_case로 전달하기 위해 설정
  jackson:
    property-naming-strategy: SNAKE_CASE

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/smswh?serverTimezone=Asia/Seoul}
    username: ${DB_USER:smswh}
    password: ${DB_PASSWORD:1234}

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect # Could not fetch the SequenceInformation from the database 에러 해결
    open-in-view: true
    hibernate:
      ddl-auto: update # update: 데이터 INSERT 후 서버 재실행해도 남아있음 / create: 서버 재실행시 INSERT된 데이터 사라짐 / none: 배포 후 사용
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database: sql_server
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB





